---
title: "Handel (2013) Adverse Selection and Inertia in Health Insurance Markets: When Nudging Hurts"
author: "Yuki KAYABA"
date: '2023-01-02'
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
#output_dir: docs
#bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# Summary of the Paper

（ひとことメモ）

- 保険マーケットにおける諸問題のうち、InertiaとAdverse Selectionの関係に注目した論文。
- いずれも保険マーケットの効率性を損なう問題として捉えられているが、両者には「Inertiaを減らして消費者が良い選択をできるようにするほどAdverse Selectionを助長する」という関係がある。
- そのため、（何らかの）NudgeによりInertiaを減らすことで、かえって経済厚生を損なう可能性がある。

## Motivation

- Investigate consumer inertia in health insurance markets.
- Potential concern of insurance markets:
  - Adverse Selection
  - Moral Hazard (hardly discussed in this paper)
  - Inertia: consumers are reluctant to make active choices
- Focus on the relationship between adverse selection and inertia.
- To do so, a choice model is developed and estimated, and using these estimates counterfactual simulation is conducted to study the impact of policies that nudge consumer toward better decisions by reducing inertia.
- The improved choices substantially exacerbate adverse selection, leading to an overall reduction in welfare ("When Nudging Hurts").

## Related Literature
- Farrell and Klemperer (2007): survey related work on switching costs and discuss how the inability of researchers to observe active or initial choices within a micro-level panel dataset confounds their ability to separately identify switching costs from persistent unobserved preference heterogeneity.

## Contribution
- Explicitly quantify the value of inertia and other micro-foundations
- Use those estimates to study the interaction between inertia and adverse selection

# Details of the Paper

## Preliminary Analysis

1. New Employees
- Compare the choices over time of the cohorts of new enrollees from years $t_{−1}$, $t_{0}$, and $t_{1}$.
- Results: while it is evident that the $t_{0}$ and $t_{−1}$ cohorts make very similar choices with the default option at $t_{1}$, the new enrollees making active choices in that year have a very different choice profile that reflects the price changes for $t_{1}$.

2. Dominated Plan Choice
- leverages a specific situation caused by the combination of plan characteristics and plan price changes in our setting. 
- As a result of the large price changes for year $t_{1}$, $PPO_{250}$ became _strictly dominated_ for certain combinations of family size and income, which determine employee premium contributions.
- Without inertia, employees must switch their options to monetary advantageous one.
- Results show that only a fraction of employees change their insurance option.

3. Adverse Selection
- The more the employees are riskier, the more likely they enroll in more comprehensive plan.

## Model

- Choice Model: consumer's choice conditional on predicted family-level ex ante medical cost risk
- Cost Model: generates the expenditure distributions

### Choice Model
- $k \in \mathcal{K}$: a family unit
- $j \in \mathcal{J}$: one of the three PPO insurance plans available after the $t_{0}$ menu change
- $t \in \mathcal{T}$: one of the three years from $t_{0}$ to $t_{2}$
- $F_{kjt}(\cdot)$: family-plan-time specific distributions of out-of-pocket health expenditures (output by the cost model)

- Each family has the following latent, v-NM expected utility:
$$
U_{kjt} = \int^{\infty}_{0} f_{kjt}(OOP)u_{k}(W_{k}, OOP, P_{kjt}, 1_{kj, t-1})dOOP,
$$
- $OOP$: a realization of medical expenses from $F_{kjt}(\cdot)$
- $W_{k}$: family-specific wealth
- $P_{kjt}$: family-time-specific premium contribution for plan $j$
- $1_{kj, t-1}$: an indicator of whether the family was enrolled in plan $j$ in the previous time period
- $u_{k}(\cdot)$: v-NM utility index and assumed to be CARA preferences:
$$
u_{k}(x) = - \frac{1}{\gamma_{k}(\mathbf{X}^{A}_{k})}e^{\gamma_{k}(\mathbf{X}^{A}_{k})x}.
$$
- $\gamma_{k}$ is a family-specific preference parameter that is known to the family but unobserved to the econometrician
- A family's overall level of consumption $x$ conditional on $OOP$ from $F_{kjt}(\cdot)$:
$$
x = W_{k} - P_{kjt} - OOP + \eta(\mathbf{X}^{B}_{kt}, Y_{k})1_{kj, t-1} + \delta_{k}(Y_{k})1_{1200} + \alpha H_{k, t-1}1_{250} + \epsilon_{kjt}(Y_{k})
$$

### Cost Model

The cost model is developed and estimated the following procedure:

- Leverage the Johns Hopkins ACG Case-Mix software package
- For each individual and open enrollment period, we use the past year of diagnoses, drugs and expenses, along with age, gender, to predict mean total expenditures for the upcoming year
- Grouping individuals into cells based on mean predicted future utilization, estimate a spending distribution for the upcoming year
- Combine individual total expense projections into the family out-of-pocket expense projections used in the choice model $F_{kjt}$

The cost model assumes that there is no private information and no moral hazard (total expenditures do not vary with $j$). While both of these phenomena have the potential to be important in health care markets, these assumptions are believed to have less impact the results, relative to inertia.

### Identification



## Estimation


## Estimation Results