---
title: "Notes: Einav, Liran, Finkelstein and Cullen (2010) Estimating Welfare in Insurance Markets Using Variation in Prices"
author: "Yuki KAYABA"
date: "1/5/2023"
site: bookdown::bookdown_site
output:
  bookdown::gitbook: default
#output_dir: docs
#bookdown::gitbook: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
```

# Summary of the Paper

（ひとことメモ）

- 

## Motivation

- Provide a graphical illustration of how standard consumer and producer theory can be used to quantify the welfare loss associated with inefficient pricing in insurance markets with selection
- Show how this welfare loss can be estimated empirically using identifying variation in the price of insurance
  - The variation, together with quantity data, allows us to estimate the demand for insurance
  - The same variation, together with cost data, allows us to estimate how insurers' costs vary as market participants endogenously respond to price
- Apply the above approach to data on health insurance form one specific company, detecting adverse selection but its impacts are small


## Related Literature

- Estimate the welfare costs of private information in insurance markets
  - Annuities: Einav, Finkelstein, and Schrimpf (2010)
  - Health Insurance: Bundorf, Levin, and Mahoney (2008); Carlin and Town (2009); Lustig (2009)

## Contribution

- Propose a complementary approach to empirical welfare analysis in insurance markets
- Make fewer assumptions about the underlying primitives, yet impose enough structure to allow meaningful welfare analysis

# Details of the Paper

## Model

### Setup and Notation

- Consumers choose from two available insurance contracts: 
  - Contract $H$, full insurance with price $p$
  - Contract $L$, no insurance available for free
- Characteristics of the insurance contracts as given, although we allow the price of insurance to be determined endogenously
- $G(\zeta)$: distribution of the population, where $\zeta$ is a vector of consumer characteristics
- $v^{H}(\zeta_{i}, p)$, $v^{L}(\zeta_{i})$: consumer $i$'s (with characteristics) utility from buying contracts $H$ and $L$, respectively
- Assume that $v^{H}(\zeta_{i}, p)$ is strictly decreasing in $p$ and that $v^{H}(\zeta_{i}, p = 0) > v^{L}(\zeta_{i})$
- $c(\zeta_{i})$: the expected monetary cost associated with the insurable risk for individual $i$

### Demand for Insurance

- Each individual makes a discrete choice of whether to buy insurance or not
- Assume that firms cannot offer different prices to different individuals
- Then, individual $i$ chooses to buy insurance if and only if $v^{H}(\zeta_{i}, p) \geq v^{L}(\zeta_{i})$
- Define $\pi(\zeta_{i}) \equiv \max \{ p: v^{H}(\zeta_{i}, p) \geq v^{L}(\zeta_{i}) \}$
- Aggregate demand for insurance is therefore given by:

$$
D(p) = \int 1(\pi(\zeta) \geq p)dG(\zeta) = \Pr(\pi(\zeta_{i}) \geq p)
$$

- Assume that $D(p)$ is strictly decreasing, continuous, and differentiable

### Supply and Equilibrium

- Consider $N \geq 2$ identical risk-neutral insurance providers, who set prices in a Nash equilibrium
- Assume that when multiple firms set the same price, individuals who decide to purchase insurance at this price choose a firm randomly
- Assume that the only costs of providing contract $H$ to individual $i$ are the insurable cost $c(\zeta_{i})$
- The above assumptions imply that at the average (expected) cost curve in the market:

$$
AC(p) = \frac{1}{D(p)} \int c(\zeta)1(\pi(\zeta) \geq p)dG(\zeta) = E(c(\zeta) \mid \pi(\zeta) \geq p)
$$

- The marginal (expected) cost curve in the market

$$
MC(p) = E(c(\zeta) \mid \pi(\zeta) = p)
$$

Add two further simplifying assumptions to straightforwardly characterize equilibrium.

1. Assume that there exists a price $\overline{p}$ such that $D(\overline{p}) > 0$ and $MC(p) < p$ for every $p > \overline{p}$. In words, we assume that it is profitable (and efficient, as we will see soon) to provide insurance to those with the highest willingness to pay for it[^1]
2. Assume that if there exists $\underline{p}$ such that $MC(\underline{p}) > \underline{p}$, then $MC(p) > p$ for all $p < \underline{p}$. 
That is, we assume that $MC(p)$ crosses the demand curve at most once[^2]

[^1]:$\pi(\zeta_{i}) = p$なるmarginal consumerを考えたとき、当然$\pi(\zeta_{i}) \geq p$を満たすので$H$を選択する。
このとき、仮定1から$p > \overline{p}$について$MC(p) < p$であるため、$p > \overline{p}$におけるmarginal consumerは$H$を選択し、かつ$MC(p)$は$p$より小さい。
各$p$についてmarginal consumerが複数いることはあり得るが（Footnote 3）、すべてのmarginal consumerについて上記が成立するので各$p >  \overline{p}$についてmarket全体の需要量は$MC(p)$を上回る。
したがって、$p >  \overline{p}$について$D(p) > MC(p)$。

[^2]:仮定1と同様にmarginal consumerを考えているので$H$を選択する。そのうえで、仮定2より、$MC(\underline{p}) > \underline{p}$なる$\underline{p}$が存在する場合、$p < \underline{p}$について$MC(p) > p$が成立する。改定1より$p >  \overline{p}$について$D(p) > MC(p)$が成立しており、仮定2の$\underline{p}$が存在しない場合はすべての$p$について$D(p) > MC(p)$となるため$D(p)$と$MC(p)$は1回も交差しない。

- These assumptions guarantee the easy to verify that these assumptions guarantee the existence and uniqueness of equilibrium
- In particular, the equilibrium is characterized by the lowest break-even price, that is, [^3]

$$
p^{*} = \min \{ p: p = AC(p) \}
$$

[^3]:各企業は一律に価格を設定するため、平均費用をすべての消費者に課す。企業はベルトラン競争を行っており、価格が一律でない場合はナッシュ均衡が存在しない。すべての企業の価格が同一であり、利潤0となる$p = AC(p)$がナッシュ均衡となる。

## Measurig Welfare

- Measure consumer surplus by _the certainty equivalent_.
- The certainty equivalent of an uncertain outcome is the amount that would make an individual indifferent between obtaining this amount for sure and obtaining the uncertain outcome.
- Denote by $e^{H}(\zeta_{i})$ and $e^{L}(\zeta_{i})$ the certainty equivalents for consumer $i$ of an allocation of contract $H$ and $L$, respectively. 
- Under the assumption that all individuals are risk-averse, the willingness to pay for insurance in given by $\pi(\zeta_{i}) = e^{H}(\zeta_{i}) - e^{L}(\zeta_{i})$
- Consumer welfare is given by:

$$
CS = \int [(e^{H}(\zeta) - p)1(\pi(\zeta_{i}) \geq p) + (e^{L}(\zeta) - p)1(\pi(\zeta_{i}) < p)]dG(\zeta)
$$

- Producer welfare is given by:

$$
PS = \int (p - c(\zeta))1(\pi(\zeta_{i}) \geq p)dG(\zeta)
$$

- Total welfare will then be given by:

$$
\begin{align}
TS &= CS + PS \\
&= \int [(e^{H}(\zeta) - c(\zeta))1(\pi(\zeta_{i}) \geq p) + e^{L}(\zeta)1(\pi(\zeta_{i}) < p)]dG(\zeta)
\end{align}
$$
**Efficient Allocation**

- It is socially efficient for individual $i$ to purchase insurance if and only if $\pi(\zeta_{i}) \geq c(\zeta_{i})$ (a first-best allocation)
- However, achieving the first best may not be feasible if there are multiple individuals with different $c(\zeta_{i})$'s who all have the same willingness to pay for contract $H$, since price is the only instrument available to affect the insurance allocation
- Therefore, it is useful to define a _constrained efficient allocation_ as the one that maximizes social welfare subject to the constraint that price is the only instrument available for screening
- It is constrained efficient for individual $i$ to purchase contract $H$ if and only if

$$
\pi(\zeta_{i}) \geq E(c(\widetilde{\zeta}) \mid \pi(\widetilde{\zeta}) = \pi(\zeta_{i}))
$$

## Graphical Representation

### Adverse Selection

- See Figure 1 of the paper
- The individuals who have the highest willingness to pay for insurance are those who, on average, have the highest expected costs
- This is represented by downward-sloping $MC$ curve
- $AC$ curve is also downward-sloping, and always above $MC$ curve[^4]
- Because average costs are always higher than marginal costs, adverse selection creates underinsurance

[^4]:Adverse Selectionでは、（グラフの左側に位置する）WTPが高い消費者ほど（期待）コストが高いため、$AC > MC$となる。

### Advantageous Selection

- See Figure 2 of the paper
- Those with more insurance have lower average costs than those with less or no insurance
- $MS$ and $AC$ curve is upward-sloping, and $AC$ is below $MC$[^5]
- Because average costs are always higher than marginal costs, adverse selection creates overinsurance

[^5]:Advantageous Selectionでは、（グラフの左側に位置する）WTPが高い消費者ほど（期待）コストが低いため、$AC < MC$となる。


## Counterfactual Simulations

